### ISSUE TITLE
"Copy as workitem attribute"

### ISSUE THREAD

**Issue by rchande** [dpoeschl/StashPop#25]
I'd love a button that puts text like

`````` C#
<WorkItem([issuenumber], "[issueurl]">```



 on the clipboard.
``````

**Comment by rchande** [comment]
Might need separate buttons for C# and VB :smile:

**Comment by dpoeschl** [comment]
We could add a paste command handler to VS that checks for a custom copy format and pastes appropriately per-language. :wink:

**Comment by dpoeschl** [comment]
@rchande  You implemented this (at least for C#, and there's a separate issue for VB) so we can close this, right?
