### ISSUE TITLE
Make "Copy as WorkItem" available from list view

### ISSUE THREAD

**Issue by rchande** [dpoeschl/StashPop#30]

**Comment by dpoeschl** [comment]
@rchande Do we really want this in the list view? Does copying multiple make sense? if you're at the point of doing this, aren't you firmly working on one work item? I'm open to adding stuff in the list view, but only if we think it might actually be used from there. I believe there's a legit use case for the email links (triage), but I'm not convinced about this yet. What would you use it for?

**Comment by rchande** [comment]
I feel like I've written tests that I wanted to add multiple WorkItem attributes to, but maybe that's niche enough that we needn't bother.

**Comment by dpoeschl** [comment]
WontFix - I think this would be a lot of noise for very little utility.
