### ISSUE TITLE
Feature Request: Add automated PR trigger buttons for optional jobs

### ISSUE THREAD

**Issue by mmitche** [dpoeschl/StashPop#48]
There are lots of optional jobs in the Jenkins config for a given repo.  It would be awesome to have a way to trigger these on demand.  For example, the test results could have "Test" buttons for jobs not yet run, with the job description.

**Comment by dpoeschl** [comment]
@mmitche The only reasonable way I can come up with to do this quickly is to have a way for users to specify these non-default test suites, and I'm considering the format:

_testSuiteSpecification:_
&nbsp;&nbsp;&nbsp;&nbsp;_scope_ `:` _suite-name_
&nbsp;&nbsp;&nbsp;&nbsp;_scope_ `:` _suite-name_ `:` _suite-name_ &nbsp;&nbsp;&nbsp;&nbsp; // The first _suite-name_ gets put in "test _suite-name_ please" unless the second _test-suite_ is already running/ran (see example)

_scope:_
&nbsp;&nbsp;&nbsp;&nbsp;_organization_
&nbsp;&nbsp;&nbsp;&nbsp;_organization_ `/` _repository_

By default, I'll prepopulate this specification with 

```
dotnet/roslyn:vsi:prtest/win/vsi/p0
dotnet/roslyn-internal:vsi:prtest/win/vsi/p0
```

Do you have any other suggestions for things you'd like pre-configured by default?

**Comment by dpoeschl** [comment]
Checked in the above proposed implementation. @mmitche If you get a chance to try it please let me know if it works for you.

**Comment by mmitche** [comment]
@dpoeschl That could work.  I'm not sure about the specifics on the GitHub implementation, but we could also simply put a file in the root of the repo that specifies the trigger phrases that should be sent to Jenkins and the text that should be shown in the GitHub UI.

**Comment by dpoeschl** [comment]
@mmitche Let me make sure I understand your proposal -- The root of the repo would check in something like ".cibuilds". Any tools could then pick up on that (including non-browser-extensions), and StashPop in particular would use it to populate the list of not-yet-run test suites.

That suggestion sounds great if we can get teams to use that convention. I'd still like to keep the user-customization option available in the extension settings for automating repositories that haven't adopted such a pattern.

**Comment by mmitche** [comment]
@dpoeschl That would be one way to do it.  It would be nice if Jenkins could inform the list, since that avoids issues with the list getting stale, but that is more difficult.  Of course, having a manual list doesn't mean automatic population couldn't replace that in the future.
