### ISSUE TITLE
Create a better icon.

### ISSUE THREAD

**Issue by dpoeschl** [dpoeschl/StashPop#5]
To replace the stock "Hello" thing or whatever it says:

![image](https://cloud.githubusercontent.com/assets/235241/11249320/fc888e42-8dda-11e5-8684-c28ed1fc53a1.png)

**Comment by dpoeschl** [comment]
Wink wink, @kuhlenh

**Comment by kuhlenh** [comment]
This is all my brain could come up with for now:
![image](https://cloud.githubusercontent.com/assets/1402694/11250200/23f39c74-8de0-11e5-9cfe-ae8d3724eea6.png)

**Comment by kuhlenh** [comment]
also what dimensions/file format do you need it in?

**Comment by dpoeschl** [comment]
@kuhlenh I removed the "-for-github" suffix.

For size, these are the sizes that Chrome uses: https://developer.chrome.com/extensions/manifest/icons (16, 48, 128), but I don't need all sizes to start with. :smile:

**Comment by dpoeschl** [comment]
(I'm also happy to have the largish banner one for the readme)
