### ISSUE TITLE
Support non-"dotnet" Jenkins hosts

### ISSUE THREAD

**Issue by dpoeschl** [dpoeschl/StashPop#57]
https://developer.chrome.com/extensions/permissions

**Comment by dpoeschl** [comment]
Need to find one to test with

**Comment by akoeplinger** [comment]
I'd volunteer https://jenkins.mono-project.com :)

**Comment by dpoeschl** [comment]
@akoeplinger Perfect - thanks!

**Comment by dpoeschl** [comment]
The current Jenkins support shows this error: "Unknown Failure - If this is a private Jenkins job, click the 'Details' button to reauthenticate and then reload this failure data." so we should distinguish between these two failure modes.

**Comment by akoeplinger** [comment]
Yes, we have an additional Xamarin-internal Jenkins, that's why it shows this for you. It works if you authenticate as the message says.

**Comment by dpoeschl** [comment]
@akoeplinger I'm confused.  Are you running a custom StashPop with permissions to https://jenkins.mono-project.com in the manifest.json?

When I look at https://github.com/mono/mono/pull/2342 I see:

![image](https://cloud.githubusercontent.com/assets/235241/11817691/ec9fdaa4-a30a-11e5-9031-62073947a9c2.png)

But when I click details on the "ARM hard float Linux" queue, I'm logged in and can see info:

![image](https://cloud.githubusercontent.com/assets/235241/11817796/8b3b8082-a30b-11e5-9a7d-216c7195a373.png)

But I still can't see anything on the PR page.

**Comment by dpoeschl** [comment]
As an aside, I'd like to add well-known and trusted Jenkins servers (like mono's) to the shipping manifest.json so that they work by default. All other unknown Jenkins servers would require permission be granted on first access.

**Comment by akoeplinger** [comment]
@dpoeschl yeah, I'm running a custom version. It seems to work fine for me:

<img width="652" alt="bildschirmfoto 2015-12-15 um 18 26 05" src="https://cloud.githubusercontent.com/assets/1376924/11818213/57e48eba-a359-11e5-9085-2d3ae65a25b6.png">

Not sure why it doesn't work for Mono's public Jenkins for you?

**Comment by dpoeschl** [comment]
@akoeplinger Awesome. It's because the shipping manifest.json _only_ allows access to the dotnet team's Jenkins server right now. I'm trying to fix that behavior for non-customized manifest.json files by 1) including more well-known jenkins servers by default and 2) allowing _any_ jenkins server to be accessed with user-granted permissions.

**Comment by dpoeschl** [comment]
Background: Chrome extensions make you declare what domains you have access to. See https://github.com/dpoeschl/StashPop/blob/master/manifest.json#L38

I was nervous about granting access to *, but I'm okay with it as long as users have to grant access per unknown jenkins server.

**Comment by dpoeschl** [comment]
So once that work is done, you shouldn't need a customized version of StashPop anymore (unless you want to do dev)

**Comment by akoeplinger** [comment]
What about not including any Jenkins url permission by default and just requesting it on-demand on first use?

**Comment by dpoeschl** [comment]
Yep, that's another option, and I tend to like that better. As a note-to-self, I'll want to verify that the permissions roam between versions and whatnot.

**Comment by akoeplinger** [comment]
@dpoeschl I took a stab at implementing this in https://github.com/dpoeschl/StashPop/pull/70. Would love to hear your feedback :smile:
