### ISSUE TITLE
Navigating to an issue inside a PR and back causes duplicate code review UI

### ISSUE THREAD

**Issue by akoeplinger** [dpoeschl/StashPop#79]
For example on this PR: https://github.com/dotnet/corefx/pull/5509

Click the link to issue `#5204` and then hit the back button in the browser.

Now the UI looks like this:
![image](https://cloud.githubusercontent.com/assets/1376924/12430542/72baa80c-bef0-11e5-8146-4e9f772df227.png)

and:
![image](https://cloud.githubusercontent.com/assets/1376924/12430548/7b8fb15c-bef0-11e5-9aca-d6529e4535d2.png)

Chrome 47.0.2526.111, OSX 10.11

**Comment by dpoeschl** [comment]
Yep, didn't add the right class to it to ensure it gets cleared.

**Comment by dpoeschl** [comment]
This is super annoying, and several people have pointed it out. Will patch & update ASAP. (/cc: @balajikris)
